// <auto-generated />
using System;
using DBPMessanger.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBPMessanger.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251122003340_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DBPMessanger.Item.ChatLogInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<DateTime>("MessageTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("message_time");

                    b.Property<long>("SenderUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("sender_user_id");

                    b.Property<long>("TargetUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id")
                        .HasName("pk_chatlog");

                    b.HasIndex("SenderUserId")
                        .HasDatabaseName("ix_chatlog_sender_user_id");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_chatlog_target_user_id");

                    b.ToTable("chatlog", (string)null);
                });

            modelBuilder.Entity("DBPMessanger.infos.AuthorityChatInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("CanView")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_view");

                    b.Property<long?>("TargetUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_user_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_authoritychat");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_authoritychat_target_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_authoritychat_user_id");

                    b.ToTable("authoritychat", (string)null);
                });

            modelBuilder.Entity("DBPMessanger.infos.AuthorityDepartmentInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("CanView")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_view");

                    b.Property<long?>("TargetUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_user_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_authoritydepartment");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_authoritydepartment_target_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_authoritydepartment_user_id");

                    b.ToTable("authoritydepartment", (string)null);
                });

            modelBuilder.Entity("DBPMessanger.infos.AuthorityUserInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("CanView")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_view");

                    b.Property<long?>("TargetUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_user_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_authorityuser");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_authorityuser_target_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_authorityuser_user_id");

                    b.ToTable("authorityuser", (string)null);
                });

            modelBuilder.Entity("DBPMessanger.infos.DepartmentInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("pk_department");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_department_parent_id");

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("DBPMessanger.infos.FavoritesInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<long?>("TargetUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_user_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_favorites");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_favorites_target_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_favorites_user_id");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("DBPMessanger.infos.LoginLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("LoginTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("login_time");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("logout_time");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_loginlog");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_loginlog_user_id");

                    b.ToTable("loginlog", (string)null);
                });

            modelBuilder.Entity("DBPMessanger.infos.MultiProfileInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("longblob")
                        .HasColumnName("image");

                    b.Property<long?>("TargetUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_user_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_multiprofile");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_multiprofile_target_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_multiprofile_user_id");

                    b.ToTable("multiprofile", (string)null);
                });

            modelBuilder.Entity("DBPMessanger.infos.UserInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birthday");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("department_id");

                    b.Property<byte[]>("Image")
                        .HasColumnType("longblob")
                        .HasColumnName("image");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("login_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Nickname")
                        .HasColumnType("longtext")
                        .HasColumnName("nickname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<int>("Zipcode")
                        .HasColumnType("int")
                        .HasColumnName("zipcode");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_user_department_id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("DBPMessanger.Item.ChatLogInfo", b =>
                {
                    b.HasOne("DBPMessanger.infos.UserInfo", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chatlog_user_sender_user_id");

                    b.HasOne("DBPMessanger.infos.UserInfo", "Target")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chatlog_user_target_user_id");

                    b.Navigation("Sender");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("DBPMessanger.infos.AuthorityChatInfo", b =>
                {
                    b.HasOne("DBPMessanger.infos.UserInfo", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .HasConstraintName("fk_authoritychat_user_target_user_id");

                    b.HasOne("DBPMessanger.infos.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_authoritychat_user_user_id");

                    b.Navigation("TargetUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DBPMessanger.infos.AuthorityDepartmentInfo", b =>
                {
                    b.HasOne("DBPMessanger.infos.UserInfo", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .HasConstraintName("fk_authoritydepartment_user_target_user_id");

                    b.HasOne("DBPMessanger.infos.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_authoritydepartment_user_user_id");

                    b.Navigation("TargetUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DBPMessanger.infos.AuthorityUserInfo", b =>
                {
                    b.HasOne("DBPMessanger.infos.UserInfo", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .HasConstraintName("fk_authorityuser_user_target_user_id");

                    b.HasOne("DBPMessanger.infos.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_authorityuser_user_user_id");

                    b.Navigation("TargetUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DBPMessanger.infos.DepartmentInfo", b =>
                {
                    b.HasOne("DBPMessanger.infos.DepartmentInfo", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_department_department_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DBPMessanger.infos.FavoritesInfo", b =>
                {
                    b.HasOne("DBPMessanger.infos.UserInfo", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .HasConstraintName("fk_favorites_user_target_user_id");

                    b.HasOne("DBPMessanger.infos.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_favorites_user_user_id");

                    b.Navigation("TargetUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DBPMessanger.infos.LoginLog", b =>
                {
                    b.HasOne("DBPMessanger.infos.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_loginlog_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DBPMessanger.infos.MultiProfileInfo", b =>
                {
                    b.HasOne("DBPMessanger.infos.UserInfo", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .HasConstraintName("fk_multiprofile_user_target_user_id");

                    b.HasOne("DBPMessanger.infos.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_multiprofile_user_user_id");

                    b.Navigation("TargetUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DBPMessanger.infos.UserInfo", b =>
                {
                    b.HasOne("DBPMessanger.infos.DepartmentInfo", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("fk_user_department_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DBPMessanger.infos.DepartmentInfo", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
